# -*- coding: utf-8 -*-
"""Decorators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SMmS1Hg2lRt1pkJ_cu_qGiSb5lKMC7dS

<h1><b>Decorators</b></h1>
"""

from time import time

def decoradora(funcao):
    def interno(*arg,**kargs):
        a = time()
        resultado = funcao(*arg,**kargs)
        print(time()-a)
        return resultado
    return interno

@decoradora
def soma(a,b):
    for i in range(a**b):
        pass
    return a+b

print(soma(10,6))